# Generated by Django 5.0.6 on 2024-06-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('descricao', models.TextField(max_length=600)),
            ],
        ),
    ]
